### ISSUE TITLE
Extension not working, can you help me?

### ISSUE THREAD

**Issue by allysonsouza** [partageit/brackets-open-in-cmder#1]
I'm trying to migrate from console2 to cmder, after migrate from Aptana to Brackets, and I've found your extension. But, when I click in "Open in cmder" from any directory of my project on Brackets, nothing happens.

I'm using Win7 x64, Brackets lastest version. I've added "C:\cmder\bin" to PATH variable. What could be causing this error?

**Comment by partageit** [comment]
Hello,
I think that the path should be 'C:\cmder', as cmder.exe is directly in cmder, not in bin.
David

**Comment by allysonsouza** [comment]
Thanks @partageit, I didn't pay attention to this. : )
