### ISSUE TITLE
Where is the PATH variable?

### ISSUE THREAD

**Issue by LpmRaven** [partageit/brackets-open-in-cmder#2]
I'm having trouble finding the PATH variable. Where can I find it?

**Comment by partageit** [comment]
Press the Windows button+Pause, go to Advanced system settings, Environment variables.
Edit the Path variable in the 'System variables' list and add a ; followed by the cmder path.
For example:
c:\the existing path;d:\another path;C:\Program Files (x86)\cmder

**Comment by LpmRaven** [comment]
Sorted. Great Help. Thank you.
