### ISSUE TITLE
[feature request] Nested directories

### ISSUE THREAD

**Issue by mrmlnc** [partageit/brackets-open-in-cmder#3]
I click on the "Open in cmder" and in cmder open the project folder. Is it possible to add functionality to open nested directories?

For example, action in ST3:
![2015-03-13_00-54-38](https://cloud.githubusercontent.com/assets/7034281/6628995/93768050-c91b-11e4-9433-0630faf84d99.png)

**Comment by partageit** [comment]
Hello,
It is possible, maybe one day ;)
David
