### ISSUE TITLE
Нажимаю Open in cmder и ничего не происходит.

### ISSUE THREAD

**Issue by IgorNovozhilov** [partageit/brackets-open-in-cmder#4]
Нажимаю Open in cmder и ничего не происходит.
sprint 3 build 1.3.0-16022 (release cd0a6aae5)

**Comment by partageit** [comment]
I thank Google translate...
I guess your problem is related to #1

**Comment by partageit** [comment]
I guess it was... closing...

**Comment by IgorNovozhilov** [comment]
-1
